/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//#include <LCD_KIT_confg.h>
#include <stdint.h>

#include "STD_Types.h"
#include "Macros.h"

#include "DIO_int.h"
#include "DIO_priv.h"

#include "NVIC_int.h"

#include "SYSTICK_int.h"
#include "SYSTICK_priv.h"

#include "EXTI0_int.h"
#include "EXTI0_priv.h"

#include "LCD_KIT_int.h"

#include "KEYBAD_int.h"

#include "../MCAL/RCC/RCC_int.h"
#include "../MCAL/RCC/RCC_priv.h"

void	_delay_ms(u32 ticks)
{
	u32 i;
	for( i = 0; i < (ticks * 500) ; i++)
	{
		asm("NOP");
	}
}

/**************** GPIO ****************/
//
//int main(void)
//{
//	RCC_voidSysClkInit();
//	RCC_voidPerClkEn(AHB,IOPAEN);
//	RCC_voidPerClkEn(AHB,IOPBEN);
//
//	DIO_voidInitialization();
//	//LCD_KIT_voidInitialization();
//
//	//KEYBAD_voidInitialization();
//
//	//LCD_KIT_voidDisplayCharacter('A');
//
//	while(1)
//	{
//		//LCD_KIT_voidDisplayCharacter('A');
//
//
////		DIO_voidSetPinValue(PortA, Pin5, Low);
////		_delay_ms(500);
////		DIO_voidSetPinValue(PortA, Pin5, High);
//
//		DIO_voidTogPinValue(PortA, Pin5);
//
//		_delay_ms(500);
//	}
//}








/************* SYSTIC & NVIC ************/

void SYSTICK_ISR(void)
{
	DIO_voidTogPinValue(PortA, Pin5);

	STK->CTRL;
}

int main(void)
{
	RCC_voidSysClkInit();
	RCC_voidPerClkEn(AHB,IOPAEN);
	RCC_voidPerClkEn(AHB,IOPCEN);

	// Enable RCC for SYS_CNFG
	RCC_voidPerClkEn(APB2,0);

	DIO_voidInitialization();

	//LCD_KIT_voidInitialization();

	SYSTICK_CallBack(SYSTICK_ISR);

	SYSTICK_voidInitializatio();
	SYSTICK_voidInterruptEnable();
	SYSTICK_voidSetReloadValue(2000000);

	NVIC_voidInit();

	EXTI_voidInitialization();
	EXTI_voidLineEnable(13);
	EXTI_voidSetSenseMode(Sense_Mode_FallingEdge, 13);

//	_delay_ms(1000);
//	DIO_voidSetPinValue(PortA, Pin5, Low);
//	_delay_ms(1000);
//	DIO_voidSetPinValue(PortA, Pin5, High);

	NVIC_voidEnableInterrupt(40);

//	Priority
//
//	NVIC_voidSetPriority(6,0b0111); //group1(01) sub 3(11)
//	NVIC_voidEnableInterrupt(7);
//	NVIC_voidSetPriority(7,0b0011); //group1(00) sub 3(11)
//
//	NVIC_voidSetPendingFlag(6);
//
//	//NVIC_voidSetPendingFlag(7);

	while(1);
}




void EXTI0_IRQHandler()
{
	SET_BIT(PORTA_ODR,5);

	_delay_ms(5000);

	NVIC_voidSetPendingFlag(7);

	SET_BIT(PORTA_ODR,5);

	//_delay_ms(5000);

	while(1);	//for nesting we put while(1)

	NVIC_voidClrPendingFlag(6);
}

void EXTI1_IRQHandler()
{
	CLR_BIT(PORTA_ODR,5);

	_delay_ms(5000);

	NVIC_voidClrPendingFlag(7);
}

void EXTI15_10_IRQHandler()
{
	DIO_voidTogPinValue(PortA, Pin5);

//	LCD_KIT_voidDisplayCharacter('A');
//	LCD_KIT_voidDisplayCharacter('B');

//	NVIC_voidClrPendingFlag(40);
//	_delay_ms(1000);

	//SET_BIT(EXTI->PR1,13);
	EXTI_voidClrInterruptFlag(13);
}












